import clsx from 'clsx';
import './globals.css';
import { Inter, Plus_Jakarta_Sans } from 'next/font/google';

const font = Plus_Jakarta_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          font.className,
          'bg-nobleBlack-700 text-white text-sm font-semibold',
        )}
      >
        {children}
      </body>
    </html>
  );
}
